// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz.DB;

#nullable disable

namespace Quiz.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quiz.Entity.Card", b =>
                {
                    b.Property<string>("CardNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<float>("Balance")
                        .HasColumnType("real");

                    b.Property<float>("Daylitransaction")
                        .HasColumnType("real");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("InsertingPasswordWrongly")
                        .HasColumnType("int");

                    b.Property<bool>("IsActice")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SetedLimitationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CardNumber");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardNumber = "5859831000619801",
                            Balance = 2000f,
                            Daylitransaction = 0f,
                            HolderName = "Armin",
                            InsertingPasswordWrongly = 0,
                            IsActice = true,
                            Password = "123",
                            SetedLimitationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CardNumber = "5859831000619802",
                            Balance = 2000f,
                            Daylitransaction = 0f,
                            HolderName = "Mehdi",
                            InsertingPasswordWrongly = 0,
                            IsActice = true,
                            Password = "123",
                            SetedLimitationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CardNumber = "5859831000619803",
                            Balance = 2000f,
                            Daylitransaction = 0f,
                            HolderName = "Ali",
                            InsertingPasswordWrongly = 0,
                            IsActice = true,
                            Password = "123",
                            SetedLimitationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CardNumber = "5859831000619804",
                            Balance = 2000f,
                            Daylitransaction = 0f,
                            HolderName = "Arash",
                            InsertingPasswordWrongly = 0,
                            IsActice = true,
                            Password = "123",
                            SetedLimitationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CardNumber = "5859831000619805",
                            Balance = 2000f,
                            Daylitransaction = 0f,
                            HolderName = "Maryam",
                            InsertingPasswordWrongly = 0,
                            IsActice = true,
                            Password = "123",
                            SetedLimitationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Quiz.Entity.TransAction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<string>("DestinationCardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("SourceCardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isSuccessful")
                        .HasColumnType("bit");

                    b.HasKey("TransactionId");

                    b.HasIndex("DestinationCardNumber");

                    b.HasIndex("SourceCardNumber");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Quiz.Entity.TransAction", b =>
                {
                    b.HasOne("Quiz.Entity.Card", "DestinationCard")
                        .WithMany("DestinationTransactions")
                        .HasForeignKey("DestinationCardNumber")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quiz.Entity.Card", "SourceCard")
                        .WithMany("SourceTransactions")
                        .HasForeignKey("SourceCardNumber")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DestinationCard");

                    b.Navigation("SourceCard");
                });

            modelBuilder.Entity("Quiz.Entity.Card", b =>
                {
                    b.Navigation("DestinationTransactions");

                    b.Navigation("SourceTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
